version: 0.0.16

branches:
  only:
    - main

artifacts:
  - path: app-0.0.1-win64.zip
    name: dist
  - path: listing.txt
    name: listing
  - path: info.txt
    name: info
    
build_script: |
  env qt5 jom qwt vc python
  where python
  python -m pip install mugideploy
  git clone https://github.com/opencor/qwt.git
  cd qwt
  qmake
  jom install
  cd ..\app
  set PATH=C:\Qwt-6.2.0\lib;%PATH%
  qmake
  jom release
  cd ..
  mugideploy collect --bin app\release\app.exe --no-vcredist
  7z a app-0.0.1-win64.zip app-0.0.1-win64
  python list.py
  python info.py

deploy:
  description: 'qwt-build'
  provider: GitHub
  auth_token:
    secure: jBN4dQaXdrv9SsDZGZXuGQJ9LlP+jPRXFq++Sbt+qo1dTFGiTIGemBMEazWuPAxc
  on:
    branch: main